-- PolyGuard B2B Merchant Dashboard Database Schema
-- PostgreSQL (Neon) Database Schema

-- Drop existing tables if needed (for fresh install)
-- DROP TABLE IF EXISTS transaction_logs CASCADE;
-- DROP TABLE IF EXISTS merchant_hashes CASCADE;
-- DROP TABLE IF EXISTS merchant_qr_codes CASCADE;
-- DROP TABLE IF EXISTS merchants CASCADE;

-- Merchants table (enhanced from existing users table)
CREATE TABLE IF NOT EXISTS merchants (
    id SERIAL PRIMARY KEY,
    user_name VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    password_salt VARCHAR(64) NOT NULL,
    company_uen VARCHAR(50) NOT NULL,
    company_name VARCHAR(255) NOT NULL,
    business_type VARCHAR(100) NOT NULL,
    company_website VARCHAR(255),
    job_position VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    email VARCHAR(255),
    
    -- Merchant verification status
    status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'suspended')),
    approved_by INTEGER REFERENCES merchants(id),
    approved_at TIMESTAMP,
    rejection_reason TEXT,
    
    -- Account metadata
    is_admin BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    last_login TIMESTAMP
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_merchants_status ON merchants(status);
CREATE INDEX IF NOT EXISTS idx_merchants_company_name ON merchants(company_name);

-- Merchant QR Codes table
CREATE TABLE IF NOT EXISTS merchant_qr_codes (
    id SERIAL PRIMARY KEY,
    merchant_id INTEGER NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
    qr_code_svg TEXT NOT NULL,
    qr_url VARCHAR(500) NOT NULL,
    
    -- QR metadata
    label VARCHAR(255),
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    
    -- Usage tracking
    scan_count INTEGER DEFAULT 0,
    last_scanned TIMESTAMP,
    
    created_at TIMESTAMP DEFAULT NOW(),
    regenerated_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_qr_merchant ON merchant_qr_codes(merchant_id);
CREATE INDEX IF NOT EXISTS idx_qr_active ON merchant_qr_codes(is_active);

-- Merchant Hashes table (for SMS authenticity)
CREATE TABLE IF NOT EXISTS merchant_hashes (
    id SERIAL PRIMARY KEY,
    merchant_id INTEGER NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
    original_message TEXT NOT NULL,
    message_hash VARCHAR(64) NOT NULL,
    
    -- Hash metadata
    purpose VARCHAR(255),
    is_verified BOOLEAN DEFAULT FALSE,
    verification_count INTEGER DEFAULT 0,
    
    created_at TIMESTAMP DEFAULT NOW(),
    expires_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_hash_merchant ON merchant_hashes(merchant_id);
CREATE INDEX IF NOT EXISTS idx_hash_value ON merchant_hashes(message_hash);

-- Transaction Logs table (QR scans and hash verifications)
CREATE TABLE IF NOT EXISTS transaction_logs (
    id SERIAL PRIMARY KEY,
    merchant_id INTEGER NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
    
    -- Transaction type
    transaction_type VARCHAR(20) NOT NULL CHECK (transaction_type IN ('qr_scan', 'hash_verification', 'qr_creation', 'hash_creation')),
    
    -- Related entities
    qr_code_id INTEGER REFERENCES merchant_qr_codes(id) ON DELETE SET NULL,
    hash_id INTEGER REFERENCES merchant_hashes(id) ON DELETE SET NULL,
    
    -- User/scanner information
    scanned_hash VARCHAR(64),
    user_info JSONB,
    ip_address VARCHAR(45),
    user_agent TEXT,
    
    -- Verification result
    verification_result VARCHAR(20) CHECK (verification_result IN ('success', 'failed', 'invalid', 'expired')),
    result_message TEXT,
    
    -- Location data (optional)
    geo_location JSONB,
    
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_logs_merchant ON transaction_logs(merchant_id);
CREATE INDEX IF NOT EXISTS idx_logs_type ON transaction_logs(transaction_type);
CREATE INDEX IF NOT EXISTS idx_logs_timestamp ON transaction_logs(created_at DESC);

-- Create default admin account (password: Admin123!)
-- Password hash created with PBKDF2: iterations=100000, salt is included in merchant record
INSERT INTO merchants (
    user_name, 
    password_hash, 
    password_salt,
    company_uen, 
    company_name, 
    business_type, 
    job_position, 
    phone_number,
    email,
    status,
    is_admin
) VALUES (
    'admin',
    '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', -- placeholder, will be regenerated by app
    'admin_salt_placeholder',
    'ADMIN001',
    'PolyGuard Admin',
    'Platform',
    'System Administrator',
    '+65-0000-0000',
    'admin@polyguard.com',
    'approved',
    TRUE
) ON CONFLICT (user_name) DO NOTHING;

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to auto-update updated_at
CREATE TRIGGER update_merchants_updated_at
    BEFORE UPDATE ON merchants
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Views for analytics

-- Merchant usage statistics view
CREATE OR REPLACE VIEW merchant_usage_stats AS
SELECT 
    m.id,
    m.user_name,
    m.company_name,
    m.status,
    COUNT(DISTINCT qr.id) as total_qr_codes,
    COUNT(DISTINCT h.id) as total_hashes,
    COALESCE(SUM(qr.scan_count), 0) as total_qr_scans,
    COUNT(DISTINCT CASE WHEN tl.transaction_type = 'qr_scan' THEN tl.id END) as total_scan_transactions,
    COUNT(DISTINCT CASE WHEN tl.transaction_type = 'hash_verification' THEN tl.id END) as total_hash_verifications,
    m.created_at,
    m.last_login
FROM merchants m
LEFT JOIN merchant_qr_codes qr ON m.id = qr.merchant_id
LEFT JOIN merchant_hashes h ON m.id = h.merchant_id
LEFT JOIN transaction_logs tl ON m.id = tl.merchant_id
WHERE m.is_admin = FALSE
GROUP BY m.id, m.user_name, m.company_name, m.status, m.created_at, m.last_login;

-- Recent transactions view
CREATE OR REPLACE VIEW recent_transactions_view AS
SELECT 
    tl.id,
    tl.merchant_id,
    m.company_name,
    tl.transaction_type,
    tl.scanned_hash,
    tl.ip_address,
    tl.verification_result,
    tl.result_message,
    tl.created_at
FROM transaction_logs tl
JOIN merchants m ON tl.merchant_id = m.id
ORDER BY tl.created_at DESC;

-- Grant permissions (adjust based on your Neon setup)
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO neondb_owner;
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO neondb_owner;
